name: Skaffold_Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [ develop ]
    types: [opened, edited, closed, reopened]
     
jobs:
  Structure_Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Skaffold Build for sample
        uses: hiberbee/github-action-skaffold@latest
        with:
          command: build
          skaffold-version: 1.14.0 
          filename: examples/structure-tests/skaffold.yaml
          
          
